### ISSUE TITLE
Odkazy na stránky

### ISSUE THREAD

**Issue by TomasRoj** [dominiksalvet/uvod_do_vhdl#1]
Přidal bych odkaz na stránku, kde se daný obsah nachází. Uživatel by pak nemusel sjíždět na Xtou stránku a pouze by kliknul na odkaz a ten by ho tam hodil.

**Comment by dominiksalvet** [comment]
@TomasRoj Velice dobrá poznámka, díky. Ty odkazy tam ve skutečnosti jsou a pouze GitHub PDF s nimi z nějakého důvodu nepracuje... Zkus si ten soubor stáhnout a dej mi, prosím, vědět, zda fungují. :smiley:

**Comment by TomasRoj** [comment]
Teď jsem to stáhnul a opravdu tam jsou. Asi bych tam dal do readme napsal, že tam opravdu jsou ale github si s nimi neumí poradit. Udělal jsem issue na github foru, zatím bych to udělal tahle.

**Comment by dominiksalvet** [comment]
@TomasRoj Až budu mít chvíli čas, nejspíš to tam dám jako upozornění. Díky! :-)

**Comment by TomasRoj** [comment]
Jestli chceš dám to tam jako pull request abych ti ušetřil čas.

**Comment by dominiksalvet** [comment]
@TomasRoj Díky, ale budu si to muset sám promyslet ... chci to podobně implementovat i v [asus-fan-control](https://github.com/dominiksalvet/asus-fan-control) ve smyslu sekce "Known Issues" nebo tak nějak ... i tak ještě jednou díky.

**Comment by TomasRoj** [comment]
Okey

**Comment by dominiksalvet** [comment]
Implementováno jako e4a4cf7.
