### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by TomasRoj** [dominiksalvet/uvod_do_vhdl#2]
Přejmenoval bych soubor SUPPORT.md na TROUBLESHOOTING.md.

**Comment by dominiksalvet** [comment]
@TomasRoj Ten soubor se záměrně jmenuje SUPPORT.md, protože soubor s takovým jménem je GitHub schopen integrovat do svých webových stránek a při vytváření Issue jej nabídne uživateli přečíst v sekci Helpful resources (napravo webového rozhraní). S TROUBLESHOOTING.md jménem to nefunguje. Viz https://github.blog/2017-07-20-support-file-support/.
